language: none

sudo: required

dist: trusty

git:
  depth: false

addons:
  sonarqube: true

jdk:
  - oraclejdk11

before_install: 
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/ubuntu trusty main" | sudo tee /etc/apt/sources.list.d/mono-official.list
  - sudo apt-get update
  - sudo apt-get install mono-complete mono-devel
  - wget -O os.deb http://oscript.io/downloads/1_0_21/deb
  - sudo dpkg -i os.deb; sudo apt install -f
  - sudo opm install 1commands
  - sudo opm install 1testrunner
  - oscript
  - wget -O bsl-language-server.jar https://github.com/1c-syntax/bsl-language-server/releases/download/v0.4.0/bsl-language-server-0.4.0.jar

install: 
  - sudo opm install

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - ./travis.sh 
